# Generated by distribution/package.sh. Publish only with the matching asset.
# Source repository visibility and binary download visibility are independent.
cask "bree" do
  version "0.3.0-alpha.1"
  sha256 "3bff96bb4c2dba09ac30c668fe408a40f93f31ec6d9b711d329f6384db0e64a7"

  url "https://github.com/yuyongyan29-dev/Bree/releases/download/v0.3.0-alpha.1/bree-aarch64-apple-darwin"
  name "Bree"
  desc "Local memory inspection for macOS"
  homepage "https://github.com/yuyongyan29-dev/Bree"

  depends_on arch: :arm64
  depends_on :macos
  container type: :naked

  binary "bree-aarch64-apple-darwin", target: "bree"
end
