# Generated by distribution/package.sh. Publish only with the matching asset.
# Use brew install --build-bottle and brew bottle to add a matching bottle block.
class Bree < Formula
  desc "Local memory inspection for macOS"
  homepage "https://github.com/yuyongyan29-dev/Bree"
  url "https://github.com/yuyongyan29-dev/Bree/releases/download/v0.3.0-alpha.7/bree-aarch64-apple-darwin", using: :nounzip
  version "0.3.0-alpha.7"
  sha256 "bd7e48682de063f3c333765c188a60bfde87ba0436c935c65f7045de6b5fcddb"
  license "GPL-3.0-only"

  bottle do
    root_url "https://github.com/yuyongyan29-dev/Bree/releases/download/v0.3.0-alpha.7"
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "663f2f4a6db6e1ed9c198dc99040a680a27e5d59db134064dd955517b7186e3c"
  end

  depends_on arch: :arm64
  depends_on macos: :golden_gate

  def install
    bin.install "bree-aarch64-apple-darwin" => "bree"
    chmod 0755, bin/"bree"
  end

  test do
    assert_equal "bree #{version}", shell_output("#{bin}/bree --version").strip
    assert_match '"schema_version":1', shell_output("#{bin}/bree license --json")
  end
end
