# Generated by distribution/package.sh. Publish only with the matching asset.
# Use brew install --build-bottle and brew bottle to add a matching bottle block.
class Bree < Formula
  desc "Local memory inspection for macOS"
  homepage "https://github.com/yuyongyan29-dev/Bree"
  url "https://github.com/yuyongyan29-dev/Bree/releases/download/v0.4.0-alpha.1/bree-aarch64-apple-darwin", using: :nounzip
  version "0.4.0-alpha.1"
  sha256 "58551029fea26c45f654f268e1317309b64935526aa9410b6b9bd780c447dde2"
  license "GPL-3.0-only"

  bottle do
    root_url "https://github.com/yuyongyan29-dev/Bree/releases/download/v0.4.0-alpha.1"
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "763332ca837ab55c434959e5b759aa57e11055884c909bd832c5bf99729697fc"
  end

  depends_on arch: :arm64
  depends_on macos: :golden_gate

  def install
    bin.install "bree-aarch64-apple-darwin" => "bree"
    chmod 0755, bin/"bree"
  end

  test do
    assert_equal "bree #{version}", shell_output("#{bin}/bree --version").strip
    assert_match '"schema_version":1', shell_output("#{bin}/bree license --json")
  end
end
